### ISSUE TITLE
mux init - credentials error

### ISSUE THREAD

**Issue by ndan** [muxinc/cli#43]
`mux init` returns credentials error while CURL is working fine

```
mux init
? What's your token ID? 1ec...
? What's your token secret? [hidden]
? Do you want to go ahead and set up a Signing Key? This is used to create tokens for signed playback policies. Yes
 ›   Error: Couldn't create a signing key pair! Are you sure your token credentials were right?
```

CURL
```
curl --location 'https://api.mux.com/system/v1/signing-keys' \
-H 'Accept: application/json' \
-u ${MUX_TOKEN_ID}:${MUX_TOKEN_SECRET}
{"total_row_count":1,"data":[{"id":"whe123","created_at":"1683369357"}]}
```

Version
```
mux version
@mux/cli/0.8.0 darwin-arm64 node-v20.0.0
```

**Comment by ndan** [comment]
I've shared credentials with the support.
I was able to setup it once with new token, but then it stoped working again.

```
mux init
? What's your token ID? b25b3dc2-53b5-442f-bccb-73b414e5f25a
? What's your token secret? [hidden]
? Do you want to go ahead and set up a Signing Key? This is used to create tokens for signed playback policies. Yes
Configuration written to: /Users/daniil/.config/@mux/cli/config.json

mux init
You are attempting to initialize with an existing configuration file! If this is intentional, please pass --force.

mux init --force
? What's your token ID? cbefc5c8-fddf-4af3-8d9c-e4b405b7261f
? What's your token secret? [hidden]
? Do you want to go ahead and set up a Signing Key? This is used to create tokens for signed playback policies. Yes
 ›   Error: Couldn't create a signing key pair! Are you sure your token credentials were right?

mux init --force
? What's your token ID? b25b3dc2-53b5-442f-bccb-73b414e5f25a
? What's your token secret? [hidden]
? Do you want to go ahead and set up a Signing Key? This is used to create tokens for signed playback policies. Yes
 ›   Error: Couldn't create a signing key pair! Are you sure your token credentials were right?
```

**Comment by jaredsmith** [comment]
That's strange -- it's working fine for me using the token ID (beginning with `b25b`) and secret to sent to support, even when I do it multiple times.

Could you please try running `DEBUG=* mux init` instead to turn on additional debugging, and perhaps that will give us an idea of why it's not working correctly for you?

**Comment by ndan** [comment]
```
DEBUG=* mux init
  @oclif/config reading core plugin /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli +0ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/package.json +0ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/oclif.manifest.json +1ms
  @oclif/config:@mux/cli using manifest from /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/oclif.manifest.json +0ms
  @oclif/config reading user plugins pjson /Users/daniil/.local/share/@mux/cli/package.json +0ms
  @oclif/config loadJSON /Users/daniil/.local/share/@mux/cli/package.json +1ms
  @oclif/config loading plugins [
  '@oclif/plugin-help',
  '@oclif/plugin-not-found',
  '@oclif/plugin-autocomplete',
  '@oclif/plugin-commands',
  '@oclif/plugin-update',
  '@oclif/plugin-warn-if-update-available',
  '@oclif/plugin-plugins'
] +0ms
  @oclif/config reading core plugin /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-autocomplete +0ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-autocomplete/package.json +4ms
  @oclif/config reading core plugin /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-commands +0ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-commands/package.json +0ms
  @oclif/config reading core plugin /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-update +0ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-update/package.json +0ms
  @oclif/config reading core plugin /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-help +0ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-help/package.json +0ms
  @oclif/config reading core plugin /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-not-found +0ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-not-found/package.json +0ms
  @oclif/config reading core plugin /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-warn-if-update-available +0ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-warn-if-update-available/package.json +0ms
  @oclif/config reading core plugin /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-plugins +0ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-plugins/package.json +0ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json +1ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-update/oclif.manifest.json +0ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-help/oclif.manifest.json +1ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-not-found/oclif.manifest.json +0ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-warn-if-update-available/oclif.manifest.json +0ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-plugins/oclif.manifest.json +0ms
  @oclif/config loadJSON /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-commands/oclif.manifest.json +1ms
  @oclif/config:@oclif/plugin-autocomplete using manifest from /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-update using manifest from /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-update/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-warn-if-update-available using manifest from /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-warn-if-update-available/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-plugins using manifest from /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-plugins/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-help using manifest from /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-commands using manifest from /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-commands/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-not-found using manifest from /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-not-found/oclif.manifest.json +0ms
  @oclif/config config done +8ms
  @oclif/config start init hook +0ms
  mux:@oclif/plugin-update:hooks:init start /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-update/lib/hooks/init +0ms
  mux:@oclif/plugin-warn-if-update-available:hooks:init start /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/plugin-warn-if-update-available/lib/hooks/init/check-update +0ms
  mux:@oclif/plugin-update:hooks:init done +62ms
  mux:@oclif/plugin-warn-if-update-available:hooks:init done +13ms
  @oclif/config init hook done +156ms
  mux init version: @oclif/command@1.8.24 argv: [ 'init' ] +0ms
  @oclif/config runCommand init [] +2ms
  @oclif/config:@mux/cli require /Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/lib/commands/init.js +167ms
  @oclif/config start prerun hook +160ms
  @oclif/config prerun hook done +1ms
? What's your token ID? d8f1...
? What's your token secret? [hidden]
? Do you want to go ahead and set up a Signing Key? This is used to create tokens for signed playback policies. Yes
  follow-redirects options {
  maxRedirects: 21,
  maxBodyLength: 10485760,
  protocol: 'https:',
  path: '/video/v1/signing-keys',
  method: 'POST',
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json',
    'User-Agent': 'Mux Node | 4.0.0',
    'Content-Length': 2
  },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: 'd8f1...:123asdf...',
  hostname: 'api.mux.com',
  port: null,
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      validateHeaderName: [Function: __node_internal_],
      validateHeaderValue: [Function: __node_internal_],
      get: [Function: get],
      request: [Function: request],
      setMaxIdleHTTPParsers: [Function: setMaxIdleHTTPParsers],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
  }
} +0ms
Error: Couldn't create a signing key pair! Are you sure your token credentials were right?
    at Object.error (/Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/errors/lib/index.js:27:15)
    at Init.error (/Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/command/lib/command.js:60:23)
    at Init.run (/Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/lib/commands/init.js:79:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Init._run (/Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/command/lib/main.js:28:9)
    at async Main._run (/Users/daniil/.asdf/installs/nodejs/20.0.0/lib/node_modules/@mux/cli/node_modules/@oclif/command/lib/command.js:43:20)
```
